# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbb449776ca9cfcf7f0ac8fb7de9032259dc9b3d891152f2f106e377d20a85be8f993d50f71df3493843b47033596236d959c0cc671de859cd3eec5075a60e96

test:
  secret_key_base: e342e631eba39b6f49ca45a0a2d0b5e8ad822f3aa6bfa63d185ec6952468eb70ff31ec23773f39bee248633d308939476590ce07e5aae49fe5aa5da1a750e0f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
